import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { HttpContext } from '@angular/common/http';
import { catchError, finalize, forkJoin, of } from 'rxjs';
import { CarteirasApiService, DashboardApiService, InsightsApiService } from '../core/api/api.services';
import { Carteira, DashboardCarteira, IncomeSummary, MarketIndicator, PortfolioEvolutionPoint, CurrencyAnalysis } from '../core/api/api.models';
import { SILENT_HTTP_ERROR } from '../core/api/silent-http-error';
import { EmptyStateComponent } from '../shared/feedback.component';
import { AssetLogoComponent } from '../shared/asset-logo.component';
import { formatMoney } from '../shared/money.util';

const money = formatMoney;
const percent = (value: number | null | undefined) => value === null || value === undefined || !Number.isFinite(value) ? 'Indisponível' : `${new Intl.NumberFormat('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value)}%`;
const shortDate = (value: string) => new Intl.DateTimeFormat('pt-BR', { day: '2-digit', month: 'short' }).format(new Date(value));
const fullDate = (value: string) => new Intl.DateTimeFormat('pt-BR', { dateStyle: 'medium' }).format(new Date(value));
type Period = '1M' | '3M' | '6M' | '1A' | 'TUDO';
type SnapshotPoint = { date: string; timestamp: number; invested: number; current: number; result: number; returnPercentage: number | null };
type ChartPoint = SnapshotPoint & { value: number; x: number; y: number };
type AllocationItem = { key: string; ticker: string; company: string; logoUrl?: string | null; moedaOriginal: string; valorAtualOriginal: number; valorAtualConvertidoBrl: number; taxaCambioUtilizada?: number | null; percentage: number; color: string };
type CurrencyExposure = { currency: string; name: string; value: number; percentage: number | null };

@Component({ standalone: true, imports: [EmptyStateComponent, FormsModule, RouterLink, AssetLogoComponent], template: `
<section class="page dashboard-page">
  <header class="page-header dashboard-header"><div><p class="eyebrow">Carteira de investimentos</p><h1>Visão geral</h1><p class="muted">Dados financeiros calculados e normalizados pelo backend.</p></div><div class="dashboard-actions"><label>Carteira <select [ngModel]="selectedId()" (ngModelChange)="changePortfolio($event)" [disabled]="portfoliosUnavailable()"><option [ngValue]="0" disabled>Selecione uma carteira</option>@for (portfolio of portfolios(); track portfolio.id) { <option [ngValue]="portfolio.id">{{ portfolio.nome }}</option> }</select></label><button type="button" class="secondary" (click)="refresh()" [disabled]="loading() || !selectedId()">Atualizar</button></div></header>
  @if (portfoliosUnavailable()) { <p class="notice warning" role="status">Não foi possível carregar a lista de carteiras. A carteira aberta continua disponível.</p> }
  @if (loading() && !dashboard()) { <section class="skeleton-grid" aria-label="Carregando indicadores">@for (item of [1, 2, 3, 4]; track item) { <article class="skeleton-card"><i></i><i></i><i></i></article> }</section> } @else if (mainError()) { <section class="panel failure-state" role="alert"><h2>Não foi possível carregar esta carteira.</h2><p>Verifique se a carteira existe e se o backend está respondendo.</p><button type="button" (click)="retry()">Tentar novamente</button></section> } @else if (dashboard(); as data) {
    @if (loading()) { <p class="notice" role="status">Atualizando dados da carteira…</p> } @if (hasSupplementaryFailure()) { <p class="notice warning" role="status">Alguns dados complementares estão indisponíveis. O resumo financeiro continua atualizado.</p> }
    <section class="hero-card hero-card-interactive"><div class="hero-summary"><span>Patrimônio atual</span><strong>{{ money(data.valorAtual) }}</strong><div class="hero-result" [class.positive]="data.resultado !== null && data.resultado >= 0" [class.negative]="data.resultado !== null && data.resultado < 0"><span>{{ signedMoney(data.resultado ?? 0) }}</span><small>{{ signedPercent(data.rentabilidadePercentual ?? 0) }}</small></div><small>Atualizado em {{ data.ultimaAtualizacao || 'data não informada' }}</small></div><section class="hero-mini-chart" [class.positive]="heroTrend().tone === 'positive'" [class.negative]="heroTrend().tone === 'negative'" [class.neutral]="heroTrend().tone === 'neutral'"><div class="hero-period-selector" aria-label="Período do mini gráfico">@for (item of periods; track item.value) { <button type="button" [class.active]="heroPeriod() === item.value" (click)="heroPeriod.set(item.value)">{{ item.label }}</button> }</div>@if (!heroFilteredEvolution().length) { <div class="hero-chart-state"><strong>Sem histórico patrimonial</strong><span>A evolução aparecerá após novas atualizações da carteira.</span></div> } @else if (heroFilteredEvolution().length === 1) { <div class="hero-chart-state single"><svg viewBox="0 0 480 120" aria-hidden="true"><circle cx="240" cy="58" r="6" class="hero-marker" /></svg><strong>Histórico em formação</strong></div> } @else { <div class="hero-chart-wrap"><svg class="hero-chart" viewBox="0 0 480 120" role="img" [attr.aria-label]="heroTrend().description" (pointermove)="selectHeroPoint($event)" (pointerdown)="selectHeroPoint($event)" (pointerleave)="hoveredHeroPoint.set(null)"><defs><linearGradient id="hero-chart-area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="currentColor" stop-opacity=".24"/><stop offset="1" stop-color="currentColor" stop-opacity="0"/></linearGradient></defs>@if (hoveredHeroPoint(); as point) { <line class="hero-reference" [attr.x1]="point.x" [attr.x2]="point.x" y1="8" y2="108"/> }<path class="hero-area" [attr.d]="heroAreaPath()"/><path class="hero-line" [attr.d]="heroLinePath()"/>@for (point of [heroChartPoints()[0], heroChartPoints().at(-1)!]; track point.timestamp) { <circle class="hero-marker" [attr.cx]="point.x" [attr.cy]="point.y" r="4.5" (focus)="hoveredHeroPoint.set(point)" (blur)="hoveredHeroPoint.set(null)" tabindex="0"><title>{{ fullDate(point.date) }}: {{ money(point.value) }}</title></circle> }</svg>@if (heroTooltip(); as tooltip) { <div class="hero-chart-tooltip" [style.left.%]="heroTooltipLeft()" role="status"><strong>{{ shortFullDate(tooltip.point.date) }}</strong><span>{{ money(tooltip.point.value) }}</span>@if (tooltip.hasVariation) { <small>{{ signedMoney(tooltip.variation) }} ({{ signedPercent(tooltip.percent) }})</small> }</div> }</div><p class="hero-trend-description">{{ heroTrend().description }}</p> }</section><a routerLink="/carteiras">Gerenciar carteira</a></section>
    <section class="metrics grid" aria-label="Resumo financeiro"><article class="metric"><span>Resultado acumulado</span><strong [class.positive]="data.resultado !== null && data.resultado > 0" [class.negative]="data.resultado !== null && data.resultado < 0">{{ money(data.resultado) }}</strong></article><article class="metric"><span>Rentabilidade</span><strong [class.positive]="data.rentabilidadePercentual !== null && data.rentabilidadePercentual > 0" [class.negative]="data.rentabilidadePercentual !== null && data.rentabilidadePercentual < 0">{{ percent(data.rentabilidadePercentual) }}</strong></article><article class="metric"><span>Total investido</span><strong>{{ money(data.valorInvestido) }}</strong></article><article class="metric"><span>Ativos</span><strong>{{ data.quantidadeAtivos }}</strong></article></section>
    <section class="dashboard-visual-grid">
      <article class="panel evolution-panel option-c-evolution"><header class="chart-header"><div><h2>Evolução patrimonial</h2>@if (evolutionSummary().hasVariation) { <span class="variation-badge" [class.positive]="evolutionSummary().variation > 0" [class.negative]="evolutionSummary().variation < 0">{{ signedMoney(evolutionSummary().variation) }} · {{ signedPercent(evolutionSummary().percent) }}</span> }</div><div class="period-selector" aria-label="Período do histórico">@for (item of periods; track item.value) { <button type="button" [class.active]="period() === item.value" (click)="period.set(item.value)">{{ item.label }}</button> }</div></header><div class="evolution-chart-side">
        @if (!filteredEvolution().length) { <div class="compact-empty">⌁<strong>Sem histórico patrimonial</strong><span>A evolução aparecerá após as primeiras atualizações da carteira.</span></div> } @else if (filteredEvolution().length === 1) { <div class="compact-empty">↗<strong>Histórico em formação</strong><span>Novos pontos serão exibidos conforme o patrimônio for atualizado.</span></div> } @else { <div class="chart-wrap"><svg class="evolution-chart" viewBox="0 0 640 290" role="img" aria-label="Gráfico da evolução patrimonial"><defs><linearGradient id="evolution-area" x1="0" x2="0" y1="0" y2="1"><stop offset="0" stop-color="var(--accent-500)" stop-opacity=".35"/><stop offset="1" stop-color="var(--accent-500)" stop-opacity="0"/></linearGradient></defs>@for (line of gridLines(); track line.y) { <line class="chart-grid-line" x1="70" x2="622" [attr.y1]="line.y" [attr.y2]="line.y"/><text class="chart-axis-label" x="62" [attr.y]="line.y + 4" text-anchor="end">{{ compactMoney(line.value) }}</text> }<path class="chart-area" [attr.d]="areaPath()"/><path class="chart-line" [attr.d]="linePath()"/>@for (point of [chartPoints()[0], chartPoints().at(-1)!]; track point.timestamp) { <circle class="chart-marker" [attr.cx]="point.x" [attr.cy]="point.y" r="5" tabindex="0" (mouseenter)="hoveredPoint.set(point)" (mouseleave)="hoveredPoint.set(null)"><title>{{ fullDate(point.date) }}: {{ money(point.value) }}</title></circle> }@for (tick of dateTicks(); track tick.timestamp) { <text class="chart-axis-label chart-date-label" [attr.x]="tick.x" y="270" text-anchor="middle">{{ shortDate(tick.date) }}</text> }</svg></div>@if (hoveredPoint(); as point) { <p class="chart-tooltip" role="status">{{ fullDate(point.date) }}: <strong>{{ money(point.value) }}</strong></p> } }</div>
      </article>
      <article class="panel allocation-panel option-c-allocation"><header><h2>Distribuição por ativo</h2><p class="muted">Participação atual</p></header>@if (allocation().length) { <div class="allocation-content"><div class="donut allocation-donut" [style.background]="donutBackground()" role="img" [attr.aria-label]="allocationAriaLabel()"><div class="donut-center"><strong>{{ money(allocationTotal(), 'BRL') }}</strong><small>Total convertido em BRL</small></div></div><div class="allocation-table-wrap"><table class="allocation-table"><thead><tr><th>Ativo</th><th>Valor</th><th>%</th><th>Participação</th></tr></thead><tbody>@for (item of allocation(); track item.key) { <tr [title]="allocationTooltip(item)"><td title="{{ item.company }}"><span class="allocation-asset"><app-asset-logo [ticker]="item.ticker" [companyName]="item.company" [logoUrl]="item.logoUrl" [size]="32" />{{ item.ticker.trim().toUpperCase() }}</span></td><td>{{ money(item.valorAtualOriginal, item.moedaOriginal) }}</td><td>{{ percent(item.percentage) }}</td><td><span class="participation-bar"><span [style.width.%]="item.percentage" [style.background]="item.color"></span></span></td></tr>}</tbody></table></div></div> } @else { <div class="compact-empty">◌<span>Sem composição disponível</span></div> }</article>
    </section>
    <section class="panel"><h2>Posições consolidadas</h2>@if (data.composicao.length) { <div class="table-scroll consolidated-table-scroll"><table class="consolidated-table"><thead><tr><th>Ativo</th><th>Classe</th><th>Quantidade</th><th>Preço médio</th><th>Cotação atual</th><th>Investido</th><th>Atual</th><th>Resultado</th></tr></thead><tbody>@for (item of data.composicao; track item.acaoId) { <tr><td><div class="asset-cell"><app-asset-logo [ticker]="item.ticker" [companyName]="item.nomeEmpresa" [logoUrl]="item.logoUrl" [size]="40" /><span><strong>{{ item.ticker.trim().toUpperCase() }}</strong><small>{{ item.nomeEmpresa }}</small></span></div></td><td>{{ item.classificacaoAlocacao }}</td><td class="numeric-cell">{{ item.quantidade }}</td><td class="numeric-cell">{{ money(item.precoMedio, item.moeda || 'BRL') }}</td><td class="numeric-cell">{{ money(item.cotacaoAtual, item.moeda || 'BRL') }}</td><td class="numeric-cell">{{ money(item.valorInvestido, item.moeda || 'BRL') }}</td><td class="numeric-cell">{{ money(item.valorAtual, item.moeda || 'BRL') }}</td><td class="numeric-cell result-cell" [class.positive]="item.resultado !== null && item.resultado > 0" [class.negative]="item.resultado !== null && item.resultado < 0">{{ signedMoney(item.resultado ?? 0, item.moeda || 'BRL') }}</td></tr> }</tbody></table></div> } @else { <app-empty-state title="Carteira sem posições" detail="Cadastre uma ação e adicione uma posição à carteira para acompanhar seus investimentos."/> }</section>
    <section class="dashboard-grid option-b-panels">
      <article class="panel risk-analysis-panel"><header><p class="eyebrow">Carteira</p><h2>Análise de risco</h2></header><div class="risk-lines"><div class="risk-line"><span class="risk-icon">◈</span><div><strong>Maior posição · {{ largestAllocation()?.ticker || '—' }}</strong><div class="risk-bar"><i [style.width.%]="largestAllocation()?.percentage || 0"></i></div></div><b>{{ percent(largestAllocation()?.percentage ?? 0) }}</b></div><div class="risk-line"><span class="risk-icon">◎</span><div><strong>Exterior</strong><div class="risk-bar"><i [style.width.%]="countryShare('EUA')"></i></div></div><b>{{ percent(countryShare('EUA')) }}</b></div><div class="risk-line"><span class="risk-icon">⌂</span><div><strong>Brasil</strong><div class="risk-bar"><i [style.width.%]="countryShare('BRASIL')"></i></div></div><b>{{ percent(countryShare('BRASIL')) }}</b></div><div class="risk-line"><span class="risk-icon">!</span><div><strong>Concentração · {{ concentrationLabel() }}</strong><div class="risk-bar"><i class="risk-warning" [style.width.%]="largestAllocation()?.percentage || 0"></i></div></div><b>{{ percent(largestAllocation()?.percentage ?? 0) }}</b></div></div></article>
      <article class="panel performance-panel"><header><p class="eyebrow">Rentabilidade</p><h2>Desempenho dos ativos</h2></header>@if (performanceItems().length) { <div class="performance-list">@for (item of performanceItems(); track item.posicaoId; let index = $index) { <div class="performance-row"><span class="rank">{{ index + 1 }}</span><app-asset-logo [ticker]="item.ticker" [companyName]="item.nomeEmpresa" [logoUrl]="item.logoUrl" [size]="34"/><strong>{{ item.ticker }}</strong><span class="performance-value" [class.positive]="(item.rentabilidadePercentual ?? 0) > 0" [class.negative]="(item.rentabilidadePercentual ?? 0) < 0">{{ signedPercent(item.rentabilidadePercentual ?? 0) }}</span><span class="performance-price">{{ money(item.cotacaoAtual, item.moeda || 'BRL') }}</span></div> }</div> } @else { <div class="central-empty"><strong>Sem posições para avaliar</strong></div> }</article>
     </section>
    <section class="option-b-currency-result" aria-label="Moedas e resultado">
      <article class="panel currency-exposure-card"><header><p class="eyebrow">MOEDAS</p><h2>Exposição por moeda</h2></header>@if (currencyExposures().length) { <div class="currency-exposure-list">@for (item of currencyExposures(); track item.currency) { <div class="currency-exposure-row"><span class="currency-flag" aria-hidden="true">{{ item.currency === 'BRL' ? '🇧🇷' : item.currency === 'USD' ? '🇺🇸' : '◉' }}</span><div class="currency-exposure-main"><div class="currency-exposure-heading"><strong>{{ item.name }}</strong><b>{{ item.percentage === null ? '—' : percent(item.percentage) }}</b></div><div class="currency-bar"><i [style.width.%]="item.percentage ?? 0"></i></div><small>{{ money(item.value, item.currency) }}</small></div></div> }</div><p class="currency-footnote">Valores preservados na moeda original.</p>@if (currencyAnalysis()?.mensagemCambio) { <small class="currency-fx-warning">{{ currencyAnalysis()?.mensagemCambio }}</small> } } @else { <div class="currency-empty">Nenhuma moeda na carteira</div> }</article>
      <article class="panel result-summary-card"><header><p class="eyebrow">RESULTADO</p><h2>Lucro e prejuízo</h2></header>@if (performanceItems().length) { <div class="result-stat-grid"><div><small>Em lucro</small><strong class="value-positive">{{ profitCount() }} ativos</strong></div><div><small>Em prejuízo</small><strong class="value-negative">{{ lossCount() }} ativos</strong></div><div><small>Resultado em BRL</small><strong [class.value-positive]="resultForCurrency('BRL') > 0" [class.value-negative]="resultForCurrency('BRL') < 0">{{ signedMoney(resultForCurrency('BRL'), 'BRL') }}</strong></div><div><small>Resultado em USD</small><strong [class.value-positive]="resultForCurrency('USD') > 0" [class.value-negative]="resultForCurrency('USD') < 0">{{ signedMoney(resultForCurrency('USD'), 'USD') }}</strong></div></div><div class="result-table-wrap"><table class="result-table"><thead><tr><th>Ativo</th><th>Resultado (moeda original)</th><th>Desempenho</th></tr></thead><tbody>@for (item of performanceItems(); track item.posicaoId) { <tr><td><span class="result-asset"><app-asset-logo [ticker]="item.ticker" [companyName]="item.nomeEmpresa" [logoUrl]="item.logoUrl" [size]="30"/><b>{{ item.ticker.trim().toUpperCase() }}</b></span></td><td [class.value-positive]="(item.resultado ?? 0) > 0" [class.value-negative]="(item.resultado ?? 0) < 0">{{ signedMoney(item.resultado ?? 0, item.moeda || 'BRL') }}</td><td><div class="result-performance"><span class="result-track"><i [class.negative]="(item.rentabilidadePercentual ?? 0) < 0" [style.width.%]="Math.min(100, Math.abs(item.rentabilidadePercentual ?? 0))"></i></span><b [class.value-positive]="(item.rentabilidadePercentual ?? 0) > 0" [class.value-negative]="(item.rentabilidadePercentual ?? 0) < 0">{{ signedPercent(item.rentabilidadePercentual ?? 0) }}</b></div></td></tr> }</tbody></table></div> } @else { <div class="result-empty">Nenhum resultado disponível</div> }</article>
    </section>
  } @else { <app-empty-state title="Selecione uma carteira" detail="Escolha uma carteira para consultar seus investimentos."/> }
</section>` })
export class InsightsDashboardPage {
  readonly Math = Math;
  readonly periods: { value: Period; label: string }[] = [{ value: '1M', label: '1M' }, { value: '3M', label: '3M' }, { value: '6M', label: '6M' }, { value: '1A', label: '1A' }, { value: 'TUDO', label: 'Tudo' }]; readonly colors = ['#10b981', '#3b82f6', '#f59e0b', '#8b5cf6', '#ec4899', '#06b6d4'];
  private readonly dashboardApi = inject(DashboardApiService); private readonly insightsApi = inject(InsightsApiService); private readonly portfoliosApi = inject(CarteirasApiService); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router);
  readonly money = money; readonly percent = percent; readonly shortDate = shortDate; readonly fullDate = fullDate; readonly selectedId = signal(Number(this.route.snapshot.paramMap.get('carteiraId')) || 0); readonly portfolios = signal<Carteira[]>([]); readonly portfoliosUnavailable = signal(false); readonly dashboard = signal<DashboardCarteira | null>(null); readonly indicators = signal<MarketIndicator[]>([]); readonly evolution = signal<PortfolioEvolutionPoint[]>([]); readonly income = signal<IncomeSummary | null>(null); readonly loading = signal(false); readonly mainError = signal(false); readonly supplementaryFailures = signal({ indicators: false, evolution: false, income: false }); readonly period = signal<Period>('TUDO'); readonly heroPeriod = signal<Period>('TUDO'); readonly hoveredPoint = signal<ChartPoint | null>(null); readonly hoveredHeroPoint = signal<ChartPoint | null>(null);
  readonly currencyAnalysis = signal<CurrencyAnalysis | null>(null);
  readonly hasSupplementaryFailure = computed(() => Object.values(this.supplementaryFailures()).some(Boolean));
  readonly sortedEvolution = computed<SnapshotPoint[]>(() => this.evolution().flatMap(point => { const date = point.timestamp ?? point.referenciaEm; const timestamp = date ? new Date(date).getTime() : NaN; const invested = point.investedAmount ?? point.valorInvestido; const current = point.currentAmount ?? point.valorAtual; const result = point.resultAmount ?? (Number.isFinite(current) && Number.isFinite(invested) ? current - invested : NaN); const returnPercentage = point.returnPercentage ?? (invested > 0 && Number.isFinite(result) ? result / invested * 100 : null); return Number.isFinite(timestamp) && Number.isFinite(invested) && Number.isFinite(current) && Number.isFinite(result) ? [{ date: date!, timestamp, invested, current, result, returnPercentage: returnPercentage !== null && Number.isFinite(returnPercentage) ? returnPercentage : null }] : []; }).sort((a, b) => a.timestamp - b.timestamp));
  readonly filteredEvolution = computed(() => { const points = this.sortedEvolution(); if (!points.length || this.period() === 'TUDO') return points; const months = this.period() === '1M' ? 1 : this.period() === '3M' ? 3 : this.period() === '6M' ? 6 : 12; const cutoff = new Date(points.at(-1)!.timestamp); cutoff.setMonth(cutoff.getMonth() - months); return points.filter(point => point.timestamp >= cutoff.getTime()); });
  readonly heroFilteredEvolution = computed(() => { const points = this.sortedEvolution(); if (!points.length || this.heroPeriod() === 'TUDO') return points; const end = points.at(-1)!.timestamp; const cutoff = new Date(end); if (this.heroPeriod() === '1M') cutoff.setDate(cutoff.getDate() - 30); else cutoff.setMonth(cutoff.getMonth() - (this.heroPeriod() === '3M' ? 3 : this.heroPeriod() === '6M' ? 6 : 12)); return points.filter(point => point.timestamp >= cutoff.getTime()); });
  readonly heroChartPoints = computed<ChartPoint[]>(() => { const points = this.heroFilteredEvolution(); if (!points.length) return []; const values = points.map(point => point.result); let min = Math.min(...values, 0); let max = Math.max(...values, 0); const spread = max - min || Math.max(Math.abs(max) * .1, 1); min -= spread * .12; max += spread * .12; const range = max - min || 1; return points.map((point, index) => ({ ...point, value: point.result, x: points.length === 1 ? 240 : 8 + index / (points.length - 1) * 464, y: 10 + (max - point.result) / range * 96 })); });
  readonly heroLinePath = computed(() => this.heroChartPoints().map((point, index) => `${index ? 'L' : 'M'} ${point.x.toFixed(2)} ${point.y.toFixed(2)}`).join(' '));
  readonly heroAreaPath = computed(() => { const points = this.heroChartPoints(); return points.length ? `M ${points[0].x.toFixed(2)} 108 ${this.heroLinePath()} L ${points.at(-1)!.x.toFixed(2)} 108 Z` : ''; });
  readonly heroTrend = computed(() => { const points = this.heroFilteredEvolution(); if (!points.length) return { tone: 'neutral' as const, description: 'Sem histórico de resultado.' }; const last = points.at(-1)!; const tone = last.result > 0 ? 'positive' as const : last.result < 0 ? 'negative' as const : 'neutral' as const; const text = tone === 'positive' ? 'lucro' : tone === 'negative' ? 'prejuízo' : 'resultado neutro'; return { tone, description: last.returnPercentage === null ? `Carteira apresenta ${text}.` : `Carteira apresenta ${text} de ${percent(last.returnPercentage)}.` }; });
  readonly heroTooltip = computed(() => { const point = this.hoveredHeroPoint(); if (!point) return null; const points = this.heroChartPoints(); const index = points.findIndex(item => item.timestamp === point.timestamp); const previous = index > 0 ? points[index - 1] : null; const variation = previous ? point.value - previous.value : 0; const hasVariation = !!previous && previous.value > 0; return { point, variation, percent: hasVariation ? variation / previous!.value * 100 : 0, hasVariation }; });
  readonly heroTooltipLeft = computed(() => { const point = this.hoveredHeroPoint(); return point ? Math.max(18, Math.min(82, point.x / 480 * 100)) : 50; });
  readonly chartPoints = computed<ChartPoint[]>(() => { const points = this.filteredEvolution(); if (!points.length) return []; const values = points.map(point => point.current); let min = Math.min(...values); let max = Math.max(...values); const spread = max - min || Math.max(Math.abs(max) * .1, 1); min -= spread * .12; max += spread * .12; const range = max - min || 1; return points.map((point, index) => ({ ...point, value: point.current, x: points.length === 1 ? 346 : 70 + index / (points.length - 1) * 552, y: 22 + (max - point.current) / range * 202 })); });
  readonly chartBounds = computed(() => { const values = this.filteredEvolution().map(point => point.current); if (!values.length) return { min: 0, max: 1 }; let min = Math.min(...values); let max = Math.max(...values); const spread = max - min || Math.max(Math.abs(max) * .1, 1); return { min: min - spread * .12, max: max + spread * .12 }; });
  readonly gridLines = computed(() => { const { min, max } = this.chartBounds(); return Array.from({ length: 5 }, (_, index) => { const ratio = index / 4; return { y: 22 + ratio * 202, value: max - ratio * (max - min) }; }); });
  readonly linePath = computed(() => this.chartPoints().map((point, index) => `${index ? 'L' : 'M'} ${point.x.toFixed(2)} ${point.y.toFixed(2)}`).join(' ')); readonly areaPath = computed(() => { const points = this.chartPoints(); return points.length ? `M ${points[0].x.toFixed(2)} 224 ${this.linePath()} L ${points.at(-1)!.x.toFixed(2)} 224 Z` : ''; }); readonly dateTicks = computed(() => { const points = this.chartPoints(); return points.length < 3 ? points : [points[0], points[Math.floor((points.length - 1) / 2)], points.at(-1)!]; });
  readonly evolutionSummary = computed(() => { const points = this.filteredEvolution(); const current = points.at(-1)?.current ?? null; const first = points[0]?.current ?? null; const hasVariation = points.length > 1 && first !== null && first > 0 && current !== null; const variation = hasVariation ? current! - first! : 0; return { current, hasVariation, variation, percent: hasVariation ? variation / first! * 100 : 0, result: points.at(-1)?.result ?? null }; });
  readonly allocation = computed<AllocationItem[]>(() => { const rows = (this.dashboard()?.composicao ?? []).filter(x => x.valorAtual !== null && (x.valorAtualConvertidoBase ?? x.valorAtual) > 0).map(x => ({ key: String(x.acaoId), ticker: x.ticker, company: x.nomeEmpresa, logoUrl: x.logoUrl, moedaOriginal: x.moeda || 'BRL', valorAtualOriginal: x.valorAtual!, valorAtualConvertidoBrl: x.valorAtualConvertidoBase ?? x.valorAtual!, taxaCambioUtilizada: x.cambioParaBase, percentage: 0, color: '' })); const total = rows.reduce((sum, x) => sum + x.valorAtualConvertidoBrl, 0); return total > 0 ? rows.map((x, i) => ({ ...x, percentage: x.valorAtualConvertidoBrl / total * 100, color: this.colors[i % this.colors.length] })) : []; });
  readonly allocationTotal = computed(() => this.allocation().reduce((sum, item) => sum + item.valorAtualConvertidoBrl, 0)); readonly donutBackground = computed(() => { const items = this.allocation(); let start = 0; return `conic-gradient(${items.map(item => { const end = start + item.percentage; const stop = `${item.color} ${start}% ${end}%`; start = end; return stop; }).join(',')})`; }); readonly allocationAriaLabel = computed(() => this.allocation().map(item => `${item.ticker}: ${money(item.valorAtualOriginal, item.moedaOriginal)}, ${percent(item.percentage)}`).join('. ')); allocationTooltip(item: AllocationItem) { const original = `Original: ${money(item.valorAtualOriginal, item.moedaOriginal)}`; const equivalent = item.moedaOriginal === 'BRL' ? '' : `\nEquivalente: ${money(item.valorAtualConvertidoBrl, 'BRL')}`; return `${item.ticker}\n${original}${equivalent}\nParticipação: ${percent(item.percentage)}`; }
  readonly performanceItems = computed(() => [...(this.dashboard()?.composicao ?? [])].filter(item => Number.isFinite(item.rentabilidadePercentual ?? NaN)).sort((a,b) => (b.rentabilidadePercentual ?? -Infinity) - (a.rentabilidadePercentual ?? -Infinity)));
  readonly currencyExposures = computed<CurrencyExposure[]>(() => { const remote = this.currencyAnalysis()?.exposicoes; if (remote?.length) return remote.map(item => ({ currency: item.moeda.toUpperCase(), name: item.nome, value: item.valorOriginal, percentage: item.percentual })); const grouped = new Map<string, number>(); for (const item of this.dashboard()?.composicao ?? []) { const currency = item.moeda?.toUpperCase(); const value = Number(item.valorAtualConvertidoBase ?? item.valorAtual); if (!currency || !Number.isFinite(value) || value <= 0) continue; grouped.set(currency, (grouped.get(currency) ?? 0) + value); } const entries = [...grouped.entries()]; const names: Record<string, string> = { BRL: 'Real brasileiro', USD: 'Dólar americano', EUR: 'Euro', GBP: 'Libra esterlina', CAD: 'Dólar canadense', JPY: 'Iene japonês' }; return entries.sort((a, b) => b[1] - a[1]).map(([currency, value]) => ({ currency, value, name: names[currency] ?? currency, percentage: entries.length === 1 ? 100 : null })); });
  readonly profitCount = computed(() => this.performanceItems().filter(item => (item.resultado ?? 0) > 0).length);
  readonly lossCount = computed(() => this.performanceItems().filter(item => (item.resultado ?? 0) < 0).length);
  resultForCurrency(currency: string): number { const remote = this.currencyAnalysis()?.resultadosPorMoeda?.find(item => item.moeda.toUpperCase() === currency); return remote ? remote.resultado : this.performanceItems().filter(item => item.moeda?.toUpperCase() === currency).reduce((sum, item) => sum + (item.resultado ?? 0), 0); }
  readonly largestAllocation = computed(() => this.allocation().find(item => item.ticker !== 'Outros') ?? this.allocation()[0] ?? null);
  countryShare(country: 'BRASIL' | 'EUA'): number { const items = this.dashboard()?.composicao ?? []; const values = items.map(item => item.valorAtualConvertidoBase ?? item.valorAtual).filter((value): value is number => value !== null && value !== undefined && Number.isFinite(value) && value > 0); const total = values.reduce((sum, value) => sum + value, 0); if (!total) return 0; return items.filter(item => item.mercado === country).map(item => item.valorAtualConvertidoBase ?? item.valorAtual).filter((value): value is number => value !== null && value !== undefined && Number.isFinite(value) && value > 0).reduce((sum, value) => sum + value, 0) / total * 100; }
  concentrationLabel(): string { const value = this.largestAllocation()?.percentage ?? 0; return value <= 20 ? 'Baixa' : value <= 40 ? 'Moderada' : 'Alta'; }
  constructor() { this.loadPortfolios(); if (this.selectedId()) { this.load(this.selectedId()); this.loadCurrencyAnalysis(this.selectedId()); } }
  private loadCurrencyAnalysis(id: number): void { const loader = (this.insightsApi as InsightsApiService & { currencyAnalysis?: InsightsApiService['currencyAnalysis'] }).currencyAnalysis; if (typeof loader !== 'function') return; const context = new HttpContext().set(SILENT_HTTP_ERROR, true); loader.call(this.insightsApi, id, context).pipe(catchError(() => of(null))).subscribe(value => this.currencyAnalysis.set(value)); }
  compactMoney(value: number): string { return new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL', notation: 'compact', maximumFractionDigits: 1 }).format(value); } shortFullDate(value: string): string { return new Intl.DateTimeFormat('pt-BR').format(new Date(value)); } dateTime(value: string): string { const date = new Date(value); return Number.isFinite(date.getTime()) ? new Intl.DateTimeFormat('pt-BR', { dateStyle: 'short', timeStyle: 'short' }).format(date) : 'Data não informada'; } signedMoney(value: number, currency = 'BRL'): string { return `${value >= 0 ? '+' : ''}${money(value, currency)}`; } signedPercent(value: number): string { return `${value >= 0 ? '+' : ''}${percent(value)}`; }
  indicatorAvailable(item: MarketIndicator): boolean { return item.disponibilidade === 'AVAILABLE' && item.valor !== null && Number.isFinite(item.valor); }
  indicatorTone(item: MarketIndicator): 'positive' | 'negative' | 'neutral' { const variation = item.variacaoPercentual; return variation === null || !Number.isFinite(variation) || variation === 0 ? 'neutral' : variation > 0 ? 'positive' : 'negative'; }
  indicatorStatus(item: MarketIndicator): string { return this.indicatorAvailable(item) ? this.indicatorTone(item) === 'positive' ? 'Em alta' : this.indicatorTone(item) === 'negative' ? 'Em queda' : 'Estável' : item.disponibilidade === 'STALE' ? 'Atualização pendente' : 'Indisponível'; }
  indicatorReason(item: MarketIndicator): string { return item.disponibilidade === 'STALE' ? 'Exibindo a última atualização válida.' : 'A fonte não retornou uma cotação válida agora.'; }
  indicatorValue(item: MarketIndicator): string { if (item.valor === null || !Number.isFinite(item.valor)) return 'Indisponível'; if (item.codigo === 'IBOV') return `${new Intl.NumberFormat('pt-BR', { maximumFractionDigits: 0 }).format(item.valor)} pts`; if (item.codigo === 'CDI') return `${percent(item.valor)} a.a.`; return money(item.valor); }
  selectHeroPoint(event: PointerEvent): void { const svg = event.currentTarget as SVGElement; const bounds = svg.getBoundingClientRect(); if (!bounds.width) return; const x = Math.max(0, Math.min(480, (event.clientX - bounds.left) / bounds.width * 480)); const point = this.heroChartPoints().reduce<ChartPoint | null>((closest, candidate) => !closest || Math.abs(candidate.x - x) < Math.abs(closest.x - x) ? candidate : closest, null); this.hoveredHeroPoint.set(point); }
  changePortfolio(id: number): void { if (!id || id === this.selectedId()) return; this.selectedId.set(id); void this.router.navigate(['/dashboard', id]); this.load(id); this.loadCurrencyAnalysis(id); } refresh(): void { if (this.selectedId()) { this.load(this.selectedId()); this.loadCurrencyAnalysis(this.selectedId()); } } retry(): void { this.refresh(); }
  private loadPortfolios(): void { this.portfoliosApi.list(0, 100).pipe(catchError(() => { this.portfoliosUnavailable.set(true); return of({ content: [] } as { content: Carteira[] }); })).subscribe(page => { this.portfolios.set(page.content); const routeId = this.selectedId(); const valid = page.content.some(item => item.id === routeId); if (!valid && page.content.length) { const first = page.content[0].id; this.selectedId.set(first); void this.router.navigate(['/dashboard', first], { replaceUrl: true }); if (!this.dashboard()) this.load(first); } }); }
  private load(id: number): void { this.loading.set(true); this.mainError.set(false); this.supplementaryFailures.set({ indicators: false, evolution: false, income: false }); const context = new HttpContext().set(SILENT_HTTP_ERROR, true); forkJoin({ dashboard: this.dashboardApi.getPortfolio(id, context), indicators: this.insightsApi.indicators(context).pipe(catchError(() => { this.supplementaryFailures.update(value => ({ ...value, indicators: true })); return of([]); })), evolution: this.insightsApi.evolution(id, context).pipe(catchError(() => { this.supplementaryFailures.update(value => ({ ...value, evolution: true })); return of([]); })), income: this.insightsApi.income(id, context).pipe(catchError(() => { this.supplementaryFailures.update(value => ({ ...value, income: true })); return of(null); })) }).pipe(finalize(() => this.loading.set(false))).subscribe({ next: data => { this.dashboard.set(data.dashboard); this.indicators.set(data.indicators); this.evolution.set(data.evolution); this.income.set(data.income); }, error: () => { this.dashboard.set(null); this.mainError.set(true); } }); }
}
