import { Component, computed, inject, signal } from '@angular/core';
import { FormsModule } from '@angular/forms';
import { ActivatedRoute, Router, RouterLink } from '@angular/router';
import { catchError, finalize, forkJoin, of } from 'rxjs';
import { CarteirasApiService, DashboardApiService, InsightsApiService } from '../core/api/api.services';
import { Carteira, DashboardCarteira, IncomeSummary, MarketIndicator, PortfolioEvolutionPoint } from '../core/api/api.models';
import { EmptyStateComponent } from '../shared/feedback.component';
import { HttpContext } from '@angular/common/http';
import { SILENT_HTTP_ERROR } from '../core/api/silent-http-error';

const money = (value: number | null | undefined) => new Intl.NumberFormat('pt-BR', { style: 'currency', currency: 'BRL' }).format(value ?? 0);
const percent = (value: number | null | undefined) => `${new Intl.NumberFormat('pt-BR', { minimumFractionDigits: 2, maximumFractionDigits: 2 }).format(value ?? 0)}%`;

@Component({
  standalone: true,
  imports: [EmptyStateComponent, FormsModule, RouterLink],
  template: `
<section class="page dashboard-page">
  <header class="page-header dashboard-header"><div><p class="eyebrow">Carteira de investimentos</p><h1>Visão geral</h1><p class="muted">Dados financeiros calculados e normalizados pelo backend.</p></div>
    <div class="dashboard-actions"><label>Carteira <select [ngModel]="selectedId()" (ngModelChange)="changePortfolio($event)" [disabled]="portfoliosUnavailable()"><option [ngValue]="0" disabled>Selecione uma carteira</option>@for (portfolio of portfolios(); track portfolio.id) { <option [ngValue]="portfolio.id">{{ portfolio.nome }}</option> }</select></label><button type="button" class="secondary" (click)="refresh()" [disabled]="loading() || !selectedId()">Atualizar</button></div>
  </header>
  @if (portfoliosUnavailable()) { <p class="notice warning" role="status">Não foi possível carregar a lista de carteiras. A carteira aberta continua disponível.</p> }
  @if (loading() && !dashboard()) {
    <section class="skeleton-grid" aria-label="Carregando indicadores">@for (item of [1, 2, 3, 4]; track item) { <article class="skeleton-card"><i></i><i></i><i></i></article> }</section>
  } @else if (mainError()) {
    <section class="panel failure-state" role="alert"><h2>Não foi possível carregar esta carteira.</h2><p>Verifique se a carteira existe e se o backend está respondendo na porta 8081.</p><button type="button" (click)="retry()">Tentar novamente</button></section>
  } @else if (dashboard(); as data) {
    @if (loading()) { <p class="notice" role="status">Atualizando dados da carteira…</p> }
    @if (hasSupplementaryFailure()) { <p class="notice warning" role="status">Alguns dados complementares estão indisponíveis. O resumo financeiro continua atualizado.</p> }
    <section class="hero-card"><div><span>Patrimônio atual</span><strong>{{ money(data.valorAtual) }}</strong><small>Atualizado em {{ data.ultimaAtualizacao || 'data não informada' }}</small></div><a routerLink="/carteiras">Gerenciar carteira</a></section>
    <section class="metrics grid" aria-label="Resumo financeiro"><article class="metric"><span>Resultado acumulado</span><strong [class.positive]="data.resultado >= 0" [class.negative]="data.resultado < 0">{{ money(data.resultado) }}</strong></article><article class="metric"><span>Rentabilidade</span><strong [class.positive]="data.rentabilidadePercentual >= 0" [class.negative]="data.rentabilidadePercentual < 0">{{ percent(data.rentabilidadePercentual) }}</strong></article><article class="metric"><span>Total investido</span><strong>{{ money(data.valorInvestido) }}</strong></article><article class="metric"><span>Ativos</span><strong>{{ data.quantidadeAtivos }}</strong></article></section>
    <section class="dashboard-grid"><article class="panel evolution-panel"><h2>Evolução patrimonial</h2>@if (evolution().length) { <svg viewBox="0 0 600 220" preserveAspectRatio="none" role="img" aria-label="Evolução patrimonial"><defs><linearGradient id="area" x1="0" x2="0" y1="0" y2="1"><stop stop-color="#10b981" stop-opacity=".35"/><stop offset="1" stop-color="#10b981" stop-opacity="0"/></linearGradient></defs><polygon [attr.points]="areaPoints()" fill="url(#area)"/><polyline [attr.points]="chartPoints()" fill="none" stroke="#10b981" stroke-width="4"/></svg> } @else { <app-empty-state title="Sem histórico disponível" detail="Novos pontos serão exibidos quando houver dados armazenados."/> }</article>
      <article class="panel allocation-panel"><h2>Distribuição por ativo</h2>@if (topAllocation().length) { <div class="donut" [style.background]="donutBackground()" aria-label="Distribuição por ativo"></div><ul class="allocation-list">@for (item of topAllocation(); track item.posicaoId; let index = $index) { <li><i [style.background]="colors[index % colors.length]"></i><span>{{ item.ticker }}</span><strong>{{ money(item.valorAtual) }}</strong></li>}</ul> } @else { <app-empty-state title="Carteira sem posições" detail="Adicione uma ação e uma posição para visualizar a distribuição."/> }</article></section>
    <section class="panel"><h2>Posições consolidadas</h2>@if (data.composicao.length) { <div class="table-scroll"><table><thead><tr><th>Ativo</th><th>Classe</th><th>Investido</th><th>Atual</th><th>Resultado</th></tr></thead><tbody>@for (item of data.composicao; track item.posicaoId) { <tr><td><strong>{{ item.ticker }}</strong><small>{{ item.nomeEmpresa }}</small></td><td>{{ item.classificacaoAlocacao }}</td><td>{{ money(item.valorInvestido) }}</td><td>{{ money(item.valorAtual) }}</td><td [class.positive]="item.resultado >= 0" [class.negative]="item.resultado < 0">{{ money(item.resultado) }}</td></tr> }</tbody></table></div> } @else { <app-empty-state title="Carteira sem posições" detail="Cadastre uma ação e adicione uma posição à carteira para acompanhar seus investimentos."/> }</section>
    <section class="dashboard-grid"><article class="panel"><h2>Indicadores de mercado</h2>@if (indicators().length) { <div class="indicators">@for (item of indicators(); track item.codigo) { <div><small>{{ item.descricao }}</small><strong>{{ item.valor === null ? 'Indisponível' : item.valor }}</strong><span class="muted">{{ item.disponibilidade === 'UNAVAILABLE' ? 'Fonte indisponível' : item.referenciaEm || 'Sem referência' }}</span></div> }</div> } @else { <p class="muted">Indicadores de mercado indisponíveis.</p> }</article><article class="panel"><h2>Proventos</h2>@if (income(); as summary) { @if (summary.disponibilidade === 'UNAVAILABLE') { <p class="muted">Dados de proventos indisponíveis para esta carteira.</p> } @else { <p>Recebidos em 12 meses <strong>{{ money(summary.recebidosUltimosDozeMeses) }}</strong></p><p>Próximos proventos <strong>{{ summary.proximosProventos === null ? 'Indisponível' : money(summary.proximosProventos) }}</strong></p> } } @else { <p class="muted">Dados de proventos indisponíveis para esta carteira.</p> }</article></section>
  } @else { <app-empty-state title="Selecione uma carteira" detail="Escolha uma carteira para consultar seus investimentos."/> }
</section>`,
})
export class InsightsDashboardPage {
  readonly colors = ['#10b981', '#00b894', '#0984e3', '#fdcb6e', '#e17055'];
  private readonly dashboardApi = inject(DashboardApiService); private readonly insightsApi = inject(InsightsApiService); private readonly portfoliosApi = inject(CarteirasApiService); private readonly route = inject(ActivatedRoute); private readonly router = inject(Router);
  readonly money = money; readonly percent = percent; readonly selectedId = signal(Number(this.route.snapshot.paramMap.get('carteiraId')) || 0); readonly portfolios = signal<Carteira[]>([]); readonly portfoliosUnavailable = signal(false); readonly dashboard = signal<DashboardCarteira | null>(null); readonly indicators = signal<MarketIndicator[]>([]); readonly evolution = signal<PortfolioEvolutionPoint[]>([]); readonly income = signal<IncomeSummary | null>(null); readonly loading = signal(false); readonly mainError = signal(false); readonly supplementaryFailures = signal({ indicators: false, evolution: false, income: false });
  readonly hasSupplementaryFailure = computed(() => Object.values(this.supplementaryFailures()).some(Boolean));
  readonly topAllocation = computed(() => this.dashboard()?.composicao ?? []);
  readonly donutBackground = computed(() => { const items = this.topAllocation(); const total = items.reduce((sum, item) => sum + Math.max(item.valorAtual, 0), 0); if (!total) return '#edf0f7'; let start = 0; const stops = items.map((item, index) => { const end = start + Math.max(item.valorAtual, 0) / total * 100; const stop = `${this.colors[index % this.colors.length]} ${start}% ${end}%`; start = end; return stop; }); return `conic-gradient(${stops.join(',')})`; });
  constructor() { this.loadPortfolios(); if (this.selectedId()) this.load(this.selectedId()); }
  changePortfolio(id: number): void { if (!id || id === this.selectedId()) return; this.selectedId.set(id); void this.router.navigate(['/dashboard', id]); this.load(id); }
  refresh(): void { if (this.selectedId()) this.load(this.selectedId()); }
  retry(): void { this.refresh(); }
  chartPoints(): string { const points = this.evolution(); if (!points.length) return ''; const values = points.map(point => point.valorAtual); const min = Math.min(...values); const range = Math.max(Math.max(...values) - min, 1); return points.map((point, index) => `${points.length === 1 ? 300 : index / (points.length - 1) * 600},${190 - (point.valorAtual - min) / range * 150}`).join(' '); }
  areaPoints(): string { const points = this.chartPoints(); return points ? `0,220 ${points} 600,220` : ''; }
  private loadPortfolios(): void { this.portfoliosApi.list(0, 100).pipe(catchError(() => { this.portfoliosUnavailable.set(true); return of({ content: [] } as { content: Carteira[] }); })).subscribe(page => { this.portfolios.set(page.content); const routeId = this.selectedId(); const valid = page.content.some(item => item.id === routeId); if (!valid && page.content.length) { const first = page.content[0].id; this.selectedId.set(first); void this.router.navigate(['/dashboard', first], { replaceUrl: true }); if (!this.dashboard()) this.load(first); } }); }
  private load(id: number): void { this.loading.set(true); this.mainError.set(false); this.supplementaryFailures.set({ indicators: false, evolution: false, income: false }); const context = new HttpContext().set(SILENT_HTTP_ERROR, true); forkJoin({ dashboard: this.dashboardApi.getPortfolio(id, context), indicators: this.insightsApi.indicators(context).pipe(catchError(() => { this.supplementaryFailures.update(value => ({ ...value, indicators: true })); return of([]); })), evolution: this.insightsApi.evolution(id, context).pipe(catchError(() => { this.supplementaryFailures.update(value => ({ ...value, evolution: true })); return of([]); })), income: this.insightsApi.income(id, context).pipe(catchError(() => { this.supplementaryFailures.update(value => ({ ...value, income: true })); return of(null); })) }).pipe(finalize(() => this.loading.set(false))).subscribe({ next: data => { this.dashboard.set(data.dashboard); this.indicators.set(data.indicators); this.evolution.set(data.evolution); this.income.set(data.income); }, error: () => { this.dashboard.set(null); this.mainError.set(true); } }); }
}
