import { Component, inject, signal } from '@angular/core';
import { ActivatedRoute, RouterLink } from '@angular/router';
import { FormsModule } from '@angular/forms';
import { AcoesApiService, CarteirasApiService, CorretorasApiService } from '../core/api/api.services';
import { Acao, Corretora, PageResponse, Posicao, PosicaoRequest } from '../core/api/api.models';
import { EmptyStateComponent, LoadingComponent } from '../shared/feedback.component';
import { AssetLogoComponent } from '../shared/asset-logo.component';
import { formatMoney as money } from '../shared/money.util';
import { BrokerLogoComponent } from '../shared/broker-logo.component';
@Component({standalone:true,imports:[FormsModule,RouterLink,EmptyStateComponent,LoadingComponent,AssetLogoComponent],template:`<section class="page"><header class="page-header"><h1>Posições</h1><a routerLink="/carteiras">Voltar</a></header><section class="panel"><h2>{{editingId?'Editar':'Nova'}} posição</h2>@if(!acoes().length||!corretoras().length){<p class="notice warning">Cadastre ações e corretoras antes de adicionar posições.</p>}<form (ngSubmit)="save()"><select [(ngModel)]="form.acaoId" name="acaoId" aria-label="Ação" required><option [ngValue]="null">Selecione a ação</option>@for(a of acoes();track a.id){<option [ngValue]="a.id">{{a.ticker}} — {{a.nomeEmpresa}}</option>}</select><select [(ngModel)]="form.corretoraId" name="corretoraId" aria-label="Corretora" required><option [ngValue]="null">Selecione a corretora</option>@for(c of corretoras();track c.id){<option [ngValue]="c.id">{{c.razaoSocial}}</option>}</select><input [(ngModel)]="form.quantidade" name="quantidade" type="number" min="0.0001" aria-label="Quantidade" required><input [(ngModel)]="form.precoMedio" name="precoMedio" type="number" min="0.01" aria-label="Preço médio" required><input [(ngModel)]="form.dataPrimeiraCompra" name="dataPrimeiraCompra" type="date" aria-label="Data da primeira compra" required><button [disabled]="!valid()||saving()">{{saving()?'Salvando…':'Salvar'}}</button></form>@if(error()){<p role="alert" class="notice error">{{error()}}</p>}</section>@if(loading()){<app-loading/>}@else if(!result().content.length){<app-empty-state title="Nenhuma posição" detail="Cadastre uma posição para começar."/>}@else{<section class="panel"><div class="table-scroll"><table><tbody>@for(p of result().content;track p.id){<tr><td><div class="asset-cell"><app-asset-logo [ticker]="p.ticker" [companyName]="p.nomeEmpresa" [logoUrl]="p.logoUrl" [size]="40" /><span><strong>{{p.ticker.trim().toUpperCase()}}</strong><small>{{p.nomeEmpresa}}</small></span></div></td><td>{{broker(p.corretoraId)}}</td><td>{{money(p.valorAtual)}}</td><td><button (click)="edit(p)" [disabled]="deleting()">Editar</button><button (click)="remove(p)" [disabled]="deleting()">{{deleting()?'Excluindo…':'Excluir'}}</button></td></tr>}</tbody></table></div></section>}</section>`})
export class PositionTablePage{private api=inject(CarteirasApiService);private actions=inject(AcoesApiService);private brokers=inject(CorretorasApiService);private route=inject(ActivatedRoute);private id=Number(this.route.snapshot.paramMap.get('carteiraId'));readonly acoes=signal<Acao[]>([]);readonly corretoras=signal<Corretora[]>([]);readonly result=signal<PageResponse<Posicao>>({content:[],page:0,size:20,totalElements:0,totalPages:0});readonly loading=signal(true);readonly saving=signal(false);readonly deleting=signal(false);readonly error=signal('');readonly money=money;editingId:number|null=null;form:PosicaoRequest={acaoId:null as any,corretoraId:null as any,quantidade:null as any,precoMedio:null as any,dataPrimeiraCompra:''};constructor(){this.actions.list(0,100).subscribe(p=>this.acoes.set(p.content));this.brokers.list(0,100).subscribe(p=>this.corretoras.set(p.content));this.load()}valid(){return!!this.form.acaoId&&!!this.form.corretoraId&&Number(this.form.quantidade)>0&&Number(this.form.precoMedio)>0&&!!this.form.dataPrimeiraCompra}load(){if(!this.id){this.loading.set(false);return}this.api.listPositionsPage(this.id).subscribe({next:r=>this.result.set(r),error:()=>this.error.set('Falha ao carregar posições'),complete:()=>this.loading.set(false)})}save(){if(!this.valid()||this.saving())return;this.saving.set(true);const op=this.editingId?this.api.updatePosition(this.id,this.editingId,this.form):this.api.createPosition(this.id,this.form);op.subscribe({next:()=>{this.editingId=null;this.load()},error:()=>this.error.set('Falha ao salvar posição'),complete:()=>this.saving.set(false)})}edit(p:Posicao){this.editingId=p.id;this.form={acaoId:p.acaoId,corretoraId:p.corretoraId,quantidade:p.quantidade,precoMedio:p.precoMedio,dataPrimeiraCompra:p.dataPrimeiraCompra}}remove(p:Posicao){if(!confirm('Excluir posição?'))return;this.deleting.set(true);this.api.deletePosition(this.id,p.id).subscribe({next:()=>this.load(),error:()=>this.error.set('Falha ao excluir posição'),complete:()=>this.deleting.set(false)})}brokerEntity(id:number){return this.corretoras().find(c=>c.id===id)??null}broker(id:number){return this.brokerEntity(id)?.razaoSocial??'—'}}
