spring.application.name=CarteiraInvestimento
spring.profiles.default=dev
server.port=8081
spring.config.import=optional:file:.env[.properties]

# HTTP clients
integration.http.connect-timeout=${HTTP_CONNECT_TIMEOUT:PT5S}
integration.http.read-timeout=${HTTP_READ_TIMEOUT:PT10S}

# External integrations
integrations.brapi.base-url=${BRAPI_BASE_URL:}
integrations.brapi.token=${BRAPI_TOKEN:}


integrations.alpha-vantage.base-url=${ALPHA_VANTAGE_BASE_URL:}
integrations.alpha-vantage.api-key=${ALPHA_VANTAGE_API_KEY:}

integrations.brasil-api.base-url=${BRASIL_API_BASE_URL:}
integrations.viacep.base-url=${VIACEP_BASE_URL:}
integrations.financial-institution.base-url=${FINANCIAL_INSTITUTION_BASE_URL:}

# Web
app.cors.allowed-origins=${CORS_ALLOWED_ORIGINS:http://localhost:4200}

# OpenAPI
springdoc.api-docs.path=${OPENAPI_API_DOCS_PATH:/api-docs}
springdoc.swagger-ui.path=${OPENAPI_SWAGGER_UI_PATH:/swagger-ui}
