package com.example.carteirainvestimento.exception;

public enum ErrorCode {
    VALIDATION_ERROR,
    RESOURCE_NOT_FOUND,
    DUPLICATE_RESOURCE,
    BUSINESS_RULE_VIOLATION,
    EXTERNAL_INTEGRATION_ERROR,
    PROVIDER_UNAUTHORIZED,
    ASSET_MARKET_MISMATCH,
    ASSET_COUNTRY_MISMATCH,
    ASSET_IN_USE,
    INTERNAL_ERROR
}
